### ISSUE TITLE
can't run it

### ISSUE THREAD

**Issue by githubxiaowei** [datang1992/Correlated-VAEs#1]

**Comment by datang1992** [comment]
Hi, can you let me know what bugs do you find? I can help fix them. Thanks.

**Comment by githubxiaowei** [comment]
just can't make it run, the npz file generated by **process_tree_data.py** can't be read by **cvae_*.py**

in process_tree_data.py
```py
np.savez(f, ratings=ratings, trust=trust, c=c, N=FLAGS.N, M=FLAGS.M)
```

in cvae_*.py
```py
def load_data(data_dir):
  npzfiles = np.load(data_dir)
  N = int(np.round(npzfiles['N']))
  M = int(np.round(npzfiles['M']))
  ratings = npzfiles['ratings']
  trust_train = np.int64(np.round(npzfiles['trust_train']))
  trust_test = np.int64(np.round(npzfiles['trust_test']))
  e_train = get_e(N, trust_train)
  e_test = get_e(N, trust_test)
  edge_id_subset = np.int32(np.round(npzfiles['edge_id_subset']))
  edge_weight = npzfiles['edge_weight']
  return N, M, ratings, trust_train, trust_test, e_train, e_test, edge_id_subset, edge_weight
```

**Comment by datang1992** [comment]
These are two different experiments... As I mentioned in the README file, the file **process_tree_data.py** produces the data for the experiment in Section 4.2.2 while the **cvae_*.py** files are the codes for the experiment in Section 4.2.3. You need to feed in the npz files for the experiment in Section 4.2.3 to make the code run following the instructions from the paper. I will add the full source code in the future.
