### ISSUE TITLE
how to get the 'original_data.npz' file

### ISSUE THREAD

**Issue by xingyuezhiji** [datang1992/Correlated-VAEs#3]
hello，i use the following code to get the original_data.npz, and then run the process_Epinions_data.py and cvae_ind.py. And I can not get the result in paper(in fact I got the value 0.1807 of NCRR) , how should I run the code? Waiting for help. Thanks a lot.

```
import numpy as np

trust_data = np.loadtxt('../trust_data.txt',dtype=int)
ratings_data = np.loadtxt('../ratings_data.txt',dtype=int)
print(ratings_data)
np.savez('original_data.npz',trust_data=trust_data,ratings_data=ratings_data)
```

**Comment by datang1992** [comment]
Hi @xingyuezhiji , thanks for trying our code. I think the way you generated the file "original_data.npz" is fine, but I am curious where did you get the files "trust_data.txt" and "ratings_data.txt"?  Did you get it [here](http://www.trustlet.org/downloaded_epinions.html)? We know that there may be multiple different Epinions datasets. Probably that is the reason. We understand that different train/test splits and different runs may yield slightly different performances, but that should not be that far away from the original results.

**Comment by datang1992** [comment]
Seems that the dataset size is correct. Are you sure what you get is 0.1807? not 0.01807? 

Also, I used python2 to run but I do not think it should have such a big difference. Can you make sure if you are running the correct file cvae_ind.py? Since the [line 170](https://github.com/datang1992/Correlated-VAEs/blob/master/src/cvae_ind.py#L170) in this file is not following the grammar with python3. If the file is correct, can you run it again and let me know what do you get for the Random test RR (printed using the code in line 170)?

**Comment by xingyuezhiji** [comment]
> Seems that the dataset size is correct. Are you sure what you get is 0.1807? not 0.01807?
> 
> Also, I used python2 to run but I do not think it should have such a big difference. Can you make sure if you are running the correct file cvae_ind.py? Since the [line 170](https://github.com/datang1992/Correlated-VAEs/blob/master/src/cvae_ind.py#L170) in this file is not following the grammar with python3. If the file is correct, can you run it again and let me know what do you get for the Random test RR (printed using the code in line 170)?

To use python3，I add the parentheses '()' after 'print'. Also, I change `f = file(FLAGS.input_data_file_name, 'rb')` into `f = open(FLAGS.input_data_file_name, 'rb')`, and change the code from [Line89-line92](https://github.com/datang1992/Correlated-VAEs/blob/3a08fe3d9bc5f5334d20602991920c73ba595a1f/src/process_Epinions_data.py#L89) into the follow code:
```
new_l = np.asarray(list(s3.intersection(s4.intersection(s5))),dtype=np.int64)
id_map = -np.ones(N, dtype=np.int64)
id_map[new_l] = np.arange(new_l.shape[0])
trust_data = trust_data.astype(np.int64)
trust_data = id_map[trust_data]
```

That is the all i have changed the code.

**Comment by datang1992** [comment]
Can you run the original code in python2 for preprocess_Epinions_data.py and cvae_ind.py again and let me know what did you get for random Test NCRR and best test NCRR, without modifying the original datasets from the website and the code? I did not see any big differences if you only change this part of the code. But we just want to make sure everything is the same in case if you forgot that you changed some other part of the code and the datasets.

Also, can you let me know why do you need to change the line 89-92? And can you let me know if you use any parameters in the files preprocess_Epinions_data.py and cvae_ind.py other than the default values?

**Comment by xingyuezhiji** [comment]
here is my running result
![20190927234243](https://user-images.githubusercontent.com/22828377/65782658-bc233c00-e180-11e9-932d-cdce444b715e.png)

**Comment by datang1992** [comment]
Can you show me the random NCRR? Seems this is not what I expect. Probably the issue happens in the dataset preprocessing.

**Comment by datang1992** [comment]
Oh I saw the random test NCRR, which is too high. That means that probably your dataset is smaller than the version we get using the default parameters from process_Epinions_data.py. Can you run the original process_Epinions_data.py again using python2, the original parameters and the original datasets, and train this model again? Thanks.

**Comment by xingyuezhiji** [comment]
okay，I try using python2 to run again

**Comment by datang1992** [comment]
Thanks. Let me know if you have further issues. I guess it is not because of version of python, but perhaps you edited some part of the code or used a different parameter and as a result the dataset size is different.

**Comment by xingyuezhiji** [comment]
> Thanks. Let me know if you have further issues. I guess it is not because of version of python, but perhaps you edited some part of the code or used a different parameter and as a result the dataset size is different.

Thanks a lot! I run the process_Epinions_data.py in python2, and then the NCRR result is correct!

**Comment by datang1992** [comment]
Glad to hear that! No problem. Let me know if you have further questions.
