### ISSUE TITLE
Learning Correlated Latent Representations with Adaptive Priors

### ISSUE THREAD

**Issue by ttgump** [datang1992/Correlated-VAEs#5]
Hi,
I read you have published another correlated VAE paper "Learning Correlated Latent Representations with Adaptive Priors". Will you provide the code of this paper? Thanks.
Best,
Tian

**Comment by datang1992** [comment]
Hi Tian,

Thanks for your interests. We will release that code once we publish it at a conference. Sorry about that and thank you for your understanding.

Best,
Da
